
const default_header_data = {
    primary: {
        menu: [
            {
                id: 1,
                parent: 0,
                title: 'Learn',
                tooltip: 'Learn description ',
                description: 'Lean description',
                href: 'https://learn.com',
                order: -10,
                children: [
                    {
                        id: 11,
                        parent: 1,
                        title: 'Getting Started',
                        tooltip: 'Getting started tooltip ',
                        description: 'Getting started description',
                        order: -2,
                        href: 'https://gettingstarted.com',
                        children: [],
                    },
                    {
                        id: 12,
                        parent: 1,
                        title: 'Training Information',
                        tooltip: 'Training information tooltip ',
                        description: 'Training information description',
                        order: -2,
                        href: 'https://Traininginformation.com',
                        children: [],
                    },
                    {
                        id: 13,
                        parent: 1,
                        title: 'Strategy Roadmaps',
                        tooltip: 'Training information tooltip ',
                        description: 'Training information description',
                        order: -2,
                        href: 'https://Traininginformation.com',
                        children: [],
                    },
                    {
                        id: 14,
                        parent: 1,
                        title: 'Documentation',
                        tooltip: 'Training information tooltip ',
                        description: 'Training information description',
                        order: -2,
                        href: 'https://Traininginformation.com',
                        children: [],
                    },
                    {
                        id: 15,
                        parent: 1,
                        title: 'Solutions',
                        tooltip: 'tooltip description ',
                        description: 'ADA description',
                        order: -1,
                        href: 'https://example1.com',
                        children: [],
                    },
                    {
                        id: 16,
                        parent: 1,
                        title: 'Shared Demo Tenants',
                        tooltip: 'Shared Demo Tenants tooltip',
                        description: 'Shared Demo Tenants description',
                        order: -1,
                        href: 'https://SharedDemoTenants.com',
                        children: [],
                    },
                    {
                        id: 17,
                        parent: 1,
                        title: 'Services Base camp',
                        tooltip: 'Service Base camp description ',
                        description: 'Service Base camp description',
                        order: -1,
                        href: 'https://ServiceBasecamp .com',
                        children: [],
                    },
                ],
            },
            {
                id: 2,
                parent: 0,
                title: 'Products',
                tooltip: 'Products tooltip ',
                description: 'Products description',
                order: -9,
                href: 'https://Products.com',
                children: [
                    {
                        id: 21,
                        parent: 2,
                        title: 'Human Capital Management',
                        tooltip: 'Human Capital Management tooltip ',
                        description: 'Human Capital Management description',
                        order: -2,
                        href: 'https://HumanCapitalManagement.com',
                        children: [],
                    },
                    {
                        id: 22,
                        parent: 2,
                        title: 'Financial Management',
                        tooltip: 'Financial management tooltip',
                        description: 'Financial management description',
                        order: -1,
                        href: 'https://Financial.management.com/',
                        children: [],
                    },
                    {
                        id: 23,
                        parent: 2,
                        title: 'Workday Payroll',
                        tooltip: 'Workday Payroll tooltip ',
                        description: 'Workday Payroll description',
                        order: -2,
                        href: 'https://Workday.Payroll.com',
                        children: [],
                    },
                    {
                        id: 24,
                        parent: 2,
                        title: 'Cross Application Services',
                        tooltip: 'Cross Application Services tooltip ',
                        description: 'Cross Application Services description',
                        order: -2,
                        href: 'https://Cross.ApplicationServices.com',
                        children: [],
                    },
                    {
                        id: 25,
                        parent: 2,
                        title: 'Workforce Management',
                        tooltip: 'Workforce Management tooltip',
                        description: 'Workforce Management description',
                        order: -1,
                        href: 'https://Workforce.Management.com/',
                        children: [],
                    },
                    {
                        id: 26,
                        parent: 2,
                        title: 'Emerging Products',
                        tooltip: 'Emerging products tooltip',
                        description: 'Emerging products description',
                        order: -1,
                        href: 'https://Emerging.products.com/',
                        children: [],
                    },
                    {
                        id: 27,
                        parent: 2,
                        title: 'All Products',
                        tooltip: 'All Products tooltip',
                        description: 'All Products description',
                        order: -1,
                        href: 'https://AllProducts.com/',
                        children: [],
                    },
                ],
            },
            {
                id: 3,
                parent: 0,
                title: 'Collaborate',
                tooltip: 'Collaborate tooltip ',
                description: 'Collaborate description',
                order: -9,
                href: 'https://Collaborate.com',
                children: [
                    {
                        id: 31,
                        parent: 3,
                        title: 'Forum',
                        tooltip: 'Forum tooltip ',
                        description: 'Forum description',
                        order: -2,
                        href: 'https://Forum.com',
                        children: [],
                    },
                    {
                        id: 32,
                        parent: 3,
                        title: 'Brainstorms',
                        tooltip: 'Brainstorms tooltip',
                        description: 'Brainstorms description',
                        order: -1,
                        href: 'https://Brainstorms.com/',
                        children: [],
                    },
                    {
                        id: 33,
                        parent: 3,
                        title: 'Events',
                        tooltip: 'Events tooltip ',
                        description: 'Events description',
                        order: -2,
                        href: 'https://Events.com',
                        children: [],
                    },
                    {
                        id: 34,
                        parent: 3,
                        title: 'User Groups',
                        tooltip: 'User Groups tooltip ',
                        description: 'User Groups description',
                        order: -2,
                        href: 'https://UserGroups.com',
                        children: [],
                    },
                    {
                        id: 35,
                        parent: 3,
                        title: 'Design Partner Group',
                        tooltip: 'Design Partner tooltip',
                        description: 'Design Partner description',
                        order: -1,
                        href: 'https://Design.Partner.com/',
                        children: [],
                    },
                    {
                        id: 36,
                        parent: 3,
                        title: 'Partner Hub',
                        tooltip: 'Partner Hub tooltip',
                        description: 'Partner Hub description',
                        order: -1,
                        href: 'https://PartnerHub.com/',
                        children: [],
                    },
                    {
                        id: 37,
                        parent: 3,
                        title: 'Community Hub',
                        tooltip: 'Community Hub tooltip',
                        description: 'Community Hub description',
                        order: -1,
                        href: 'https://CommunityHub.com/',
                        children: [],
                    },
                ],
            },
            {
                id: 4,
                parent: 0,
                title: 'Feature Release',
                tooltip: 'Collaborate tooltip ',
                description: 'Collaborate description',
                order: -9,
                href: 'https://Collaborate.com',
                children: [
                    {
                        id: 41,
                        parent: 4,
                        title: 'Feature Release Guidebook',
                        tooltip: 'Forum tooltip ',
                        description: 'Forum description',
                        order: -2,
                        href: 'https://Forum.com',
                        children: [],
                    },
                    {
                        id: 42,
                        parent: 4,
                        title: 'Release Center',
                        tooltip: 'Brainstorms tooltip',
                        description: 'Brainstorms description',
                        order: -1,
                        href: 'https://Brainstorms.com/',
                        children: [],
                    },
                    {
                        id: 43,
                        parent: 4,
                        title: 'Release Notes',
                        tooltip: 'Events tooltip ',
                        description: 'Events description',
                        order: -2,
                        href: 'https://Events.com',
                        children: [],
                    },
                ],
            },
            {
                id: 5,
                parent: 0,
                title: 'Get Help',
                tooltip: 'Collaborate tooltip ',
                description: 'Collaborate description',
                order: -9,
                href: 'https://Collaborate.com',
                children: [
                    {
                        id: 51,
                        parent: 5,
                        title: 'Data Center Status',
                        tooltip: 'Forum tooltip ',
                        description: 'Forum description',
                        order: -2,
                        href: 'https://Forum.com',
                        children: [],
                    },
                    {
                        id: 52,
                        parent: 5,
                        title: 'Troubleshooting Resources',
                        tooltip: 'Brainstorms tooltip',
                        description: 'Brainstorms description',
                        order: -1,
                        href: 'https://Brainstorms.com/',
                        children: [],
                    },
                    {
                        id: 53,
                        parent: 5,
                        title: 'Customer Alerts',
                        tooltip: 'Events tooltip ',
                        description: 'Events description',
                        order: -2,
                        href: 'https://Events.com',
                        children: [],
                    },
                    {
                        id: 54,
                        parent: 5,
                        title: 'Service Alerts',
                        tooltip: 'User Groups tooltip ',
                        description: 'User Groups description',
                        order: -2,
                        href: 'https://UserGroups.com',
                        children: [],
                    },
                    {
                        id: 55,
                        parent: 5,
                        title: 'Tenant Update Schedule',
                        tooltip: 'Design Partner tooltip',
                        description: 'Design Partner description',
                        order: -1,
                        href: 'https://Design.Partner.com/',
                        children: [],
                    },
                    {
                        id: 56,
                        parent: 5,
                        title: 'Training Update Schedule',
                        tooltip: 'Partner Hub tooltip',
                        description: 'Partner Hub description',
                        order: -1,
                        href: 'https://PartnerHub.com/',
                        children: [],
                    },
                    {
                        id: 57,
                        parent: 5,
                        title: 'NSC Hub',
                        tooltip: 'Community Hub tooltip',
                        description: 'Community Hub description',
                        order: -1,
                        href: 'https://CommunityHub.com/',
                        children: [],
                    },
                ],
            },
            {
                id: 6,
                parent: 0,
                title: 'Manage',
                tooltip: 'Collaborate tooltip ',
                description: 'Collaborate description',
                order: -9,
                href: 'https://Collaborate.com',
                children: [
                    {
                        id: 61,
                        parent: 6,
                        title: 'Cases',
                        tooltip: 'Forum tooltip ',
                        description: 'Forum description',
                        order: -2,
                        href: 'https://Forum.com',
                        children: [],
                    },
                    {
                        id: 62,
                        parent: 6,
                        title: 'Users',
                        tooltip: 'Brainstorms tooltip',
                        description: 'Brainstorms description',
                        order: -1,
                        href: 'https://Brainstorms.com/',
                        children: [],
                    },
                    {
                        id: 63,
                        parent: 6,
                        title: 'Training',
                        tooltip: 'Events tooltip ',
                        description: 'Events description',
                        order: -2,
                        href: 'https://Events.com',
                        children: [],
                    },
                    {
                        id: 64,
                        parent: 6,
                        title: 'Tenants',
                        tooltip: 'User Groups tooltip ',
                        description: 'User Groups description',
                        order: -2,
                        href: 'https://UserGroups.com',
                        children: [],
                    },
                    {
                        id: 65,
                        parent: 6,
                        title: 'My Organization',
                        tooltip: 'Design Partner tooltip',
                        description: 'Design Partner description',
                        order: -1,
                        href: 'https://Design.Partner.com/',
                        children: [],
                    },
                    {
                        id: 36,
                        parent: 3,
                        title: 'Consulting',
                        tooltip: 'Partner Hub tooltip',
                        description: 'Partner Hub description',
                        order: -1,
                        href: 'https://PartnerHub.com/',
                        children: [],
                    },
                    {
                        id: 67,
                        parent: 6,
                        title: 'Reports',
                        tooltip: 'Community Hub tooltip',
                        description: 'Community Hub description',
                        order: -1,
                        href: 'https://CommunityHub.com/',
                        children: [],
                    },
                ],
            },
        ],
    },
    notification: {
        notify: true,
        redirectUrl: 'https://uat-workdayinc.cs167.force.com/workdaycustomercenter/apex/CC_ProactiveNotifications',
    },
    profile: {
        avatar: {
            // data: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==',
            data: 'https://www.w3schools.com/css/paris.jpg',
            'mime-type': 'thing',
        },
        userInfo: {
            username: 'cbillings',
            firstName: 'Christine',
            lastName: 'billings',
            href: 'https://community.workday.com/users/cbillings',
            viewProfileLabel: 'Profile',
        },
        menu: [
            {
                id: 1,
                title: 'Messages',
                icon: 'activityStreamIcon',
                tooltip: 'tooltip description ',
                description: 'ADA description',
                href: 'http://www.workday.com',
                order: -4,
                children: [],
            },
            {
                id: 2,
                title: 'Settings',
                tooltip: 'tooltip description 2',
                icon: 'gearIcon',
                description: 'ADA description',
                href: 'https://community.workday.com',
                order: -3,
                children: [],
            },
            {
                id: 3,
                title: 'Subscriptions',
                tooltip: 'tooltip description 3',
                icon: 'checkCircleIcon',
                description: 'ADA description',
                href: 'https://link3',
                order: -2,
                children: [],
            },
            {
                id: 4,
                title: 'Bookmarks',
                icon: 'mediaMylearningIcon',
                tooltip: 'tooltip description 4',
                description: 'ADA description',
                href: 'https://link4',
                order: -1,
                children: [],
            },
            {
                id: 5,
                title: 'Activity',
                icon: 'chartIcon',
                tooltip: 'tooltip description 4',
                description: 'ADA description',
                href: 'https://link4',
                order: -1,
                children: [],
            },
            {
                id: 6,
                title: 'Updates & Rewards',
                icon: 'trophyIcon',
                tooltip: 'tooltip description 4',
                description: 'ADA description',
                href: 'https://link4',
                order: -1,
                children: [],
            },
            {
                id: 7,
                title: 'Customer Care',
                icon: 'timelineMilestoneIcon',
                tooltip: 'tooltip description 4',
                description: 'ADA description',
                href: 'https://link4',
                order: -1,
                children: [],
            },
            {
                id: 8,
                title: 'Sign Out',
                icon: 'signoutIcon',
                tooltip: 'tooltip description 4',
                description: 'ADA description',
                href: 'https://link4',
                order: -1,
                children: [],
            },
        ],
    },
    utility: {
        menu: [
            {
                id: 109,
                title: 'Workday Success Plans',
                tooltip: 'Workday Success Plans',
                description: 'Access exclusive resources, tools, and expertise to help you reach your business goals.',
                href: 'https://utilitylink',
                order: -4,
                children: [],
                icon: 'personStarIcon',
            },
            {
                id: 110,
                title: 'Administrators Guide',
                tooltip: 'Administrators Guide',
                description: 'Read documentation for Workday products',
                href: 'https://utilitylink2',
                order: -3,
                children: [],
                icon: 'openBookIcon',
            },
            {
                id: 111,
                title: 'Workday  Learning Center',
                tooltip: 'Workday  Learning Center',
                description: 'Discover information related to training',
                href: 'https://utilitylink3',
                order: -2,
                children: [],
                icon: 'handLeafIcon',
            },
            {
                id: 112,
                title: 'eBooks',
                tooltip: 'eBooks',
                description: 'View the electronic couse manuals for your product training, hosted on Vital Source',
                href: 'https://utilitylink4',
                order: -1,
                children: [],
                icon: 'powerOfOneIcon',
            },
            {
                id: 113,
                title: 'Workday Partner Center~Services and Software',
                tooltip: 'Workday Partner Center',
                description: 'Manage deployments, contacts, cases, and reports in a hub made for Services partners.',
                href: 'https://utilitylink4',
                order: -1,
                children: [],
                icon: 'handshakePlusIcon',
            },
            {
                id: 114,
                title: 'Workday Partner Center~Channel',
                tooltip: 'Workday Partner Center',
                description: 'Register leads and run reports on your opportunities.',
                href: 'https://utilitylink4',
                order: -1,
                children: [],
                icon: 'handshakeIcon',
            },
        ],
    },
};

var skipTo = 'main-div'
var sticky = true;

ReactDOM.render(React.createElement(Cmty.GlobalHeader, { menus: default_header_data, skipTo, sticky, searchProps: { redirectPath: '/global-search' } }), document.getElementById('react-header-div'));
