
const default_header_data = {
    "language": "en",
    "contactNumber": null,
    "contactId": null,
    "utility": {
        "menu": [
            {
                "type": "Utility",
                "tooltip": "Workday Learning Center",
                "title": "Workday Learning Center",
                "parent": null,
                "order": 150,
                "level": "1",
                "id": "aTI4X0000008OJZWA2",
                "icon": "handleafIcon",
                "href": "https://wd5.myworkday.com/workday",
                "description": "Engage with product training from the Workday Learning Center.",
                "children": []
            },
            {
                "type": "Utility",
                "tooltip": "Workday Success Plans",
                "title": "Workday Success Plans",
                "parent": null,
                "order": 160,
                "level": "1",
                "id": "aTI4X0000008OJaWAM",
                "icon": "personStarIcon",
                "href": "https://gateway.on24.com/wcc/eh/2345846/workday-success-plans",
                "description": "Access exclusive resources, tools, and expertise to help you reach your business goals.",
                "children": []
            },
            {
                "type": "Utility",
                "tooltip": "Administrator Guide",
                "title": "Administrator Guide",
                "parent": null,
                "order": 170,
                "level": "1",
                "id": "aTI4X0000008OJbWAM",
                "icon": "chartBarScatterIcon",
                "href": "https://doc.workday.com",
                "description": "Find step-by-step information to help you plan for, configure, and use Workday features.",
                "children": []
            },
            {
                "type": "Utility",
                "tooltip": "eBooks",
                "title": "eBooks",
                "parent": null,
                "order": 180,
                "level": "1",
                "id": "aTI4X0000008OJcWAM",
                "icon": "powerOfOneIcon",
                "href": "https://bc.vitalsource.com/tenants/workday_saml/bookshelf",
                "description": "View the electronic course manuals for your product training, hosted on VitalSource®.",
                "children": []
            },
            {
                "type": "Utility",
                "tooltip": "Workday Partner Center (Channel)",
                "title": "Workday Partner Center ~ Channel",
                "parent": null,
                "order": 190,
                "level": "1",
                "id": "aTI4X0000008OJdWAM",
                "icon": "handshakeIcon",
                "href": "https://workdayinc.force.com/channelpartnercenter",
                "description": "Register leads and run reports on your opportunities.",
                "children": []
            },
            {
                "type": "Utility",
                "tooltip": "Workday Partner Center (Services & Software)",
                "title": "Workday Partner Center ~ Services and Software",
                "parent": null,
                "order": 200,
                "level": "1",
                "id": "aTI4X0000008OJeWAM",
                "icon": "handshakePlusIcon",
                "href": "https://workdayinc.force.com/partnercenter",
                "description": "Manage deployments, contacts, cases, and reports in a hub made for Services partners.",
                "children": []
            }
        ]
    },
    "profile": {
        "menu": [
            {
                "type": "Profile",
                "tooltip": "Bookmarks",
                "title": "Bookmarks",
                "parent": null,
                "order": 90,
                "level": "1",
                "id": "aTI4X0000008OJTWA2",
                "icon": "mediaMylearningIcon",
                "href": "https://community.workday.com/bookmarks",
                "description": "Where a user accesses content they have bookmarked",
                "children": []
            },
            {
                "type": "Profile",
                "tooltip": "Collaborate Updates",
                "title": "Collaborate Updates",
                "parent": null,
                "order": 100,
                "level": "1",
                "id": "aTI4X0000008OJXWA2",
                "icon": "trophyIcon",
                "href": "https://collaborate.workday.com/t5/notificationfeed/page",
                "description": "Where a user sees the recent activity for their community participation",
                "children": []
            },
            {
                "type": "Profile",
                "tooltip": "Content Admin",
                "title": "Content Admin",
                "parent": null,
                "order": 110,
                "level": "1",
                "id": "aTI4X0000008OJYWA2",
                "icon": "timelineMilestoneIcon",
                "href": "https://community.workday.com/content-administration",
                "description": "Where workmates go to author community articles",
                "children": []
            },
            {
                "type": "Profile",
                "tooltip": "Settings",
                "title": "Settings",
                "parent": null,
                "order": 120,
                "level": "1",
                "id": "aTI4X0000008OJUWA2",
                "icon": "gearIcon",
                "href": "https://resourcecenter.workday.com/en-us/wrc/settings.html",
                "description": "Where a user manages their MFA, privacy and case portal settings",
                "children": []
            },
            {
                "type": "Profile",
                "tooltip": "Subscriptions",
                "title": "Subscriptions",
                "parent": null,
                "order": 130,
                "level": "1",
                "id": "aTI4X0000008OJVWA2",
                "icon": "checkCircleIcon",
                "href": "https://community.workday.com/message-subscribe",
                "description": "Where a user manages subscriptions to content areas",
                "children": []
            }
        ]
    },
    "primary": {
        "menu": [
            {
                "type": "Primary",
                "tooltip": "Learn menu",
                "title": "Learn",
                "parent": null,
                "order": 10,
                "level": "1",
                "id": "aTI4X0000008OIyWAM",
                "icon": null,
                "href": null,
                "description": "Getting started and learning-focused resources",
                "children": [
                    {
                        "type": "Primary",
                        "tooltip": "Get Started",
                        "title": "Get Started",
                        "parent": "aTI4X0000008OIyWAM",
                        "order": 10,
                        "level": "2",
                        "id": "aTI4X0000008OIzWAM",
                        "icon": null,
                        "href": "https://community.workday.com/learn/get-started",
                        "description": "Organized getting started info for customers",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Resources",
                        "title": "Resources",
                        "parent": "aTI4X0000008OIyWAM",
                        "order": 20,
                        "level": "2",
                        "id": "aTI4X0000008OJ0WAM",
                        "icon": null,
                        "href": "https://community.workday.com/learn/resources",
                        "description": "Organized links to official documentation pages",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Training Information",
                        "title": "Training Information",
                        "parent": "aTI4X0000008OIyWAM",
                        "order": 30,
                        "level": "2",
                        "id": "aTI4X0000008OJ1WAM",
                        "icon": null,
                        "href": "https://community.workday.com/learn/training",
                        "description": "Training offerings and quick links",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Solutions",
                        "title": "Solutions",
                        "parent": "aTI4X0000008OIyWAM",
                        "order": 40,
                        "level": "2",
                        "id": "aTI4X0000008OJ2WAM",
                        "icon": null,
                        "href": "https://community.workday.com/learn/solutions",
                        "description": "Solutions and toolkits for customers and partners for implementing in their Workday tenants",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Strategy Roadmaps",
                        "title": "Strategy Roadmaps",
                        "parent": "aTI4X0000008OIyWAM",
                        "order": 50,
                        "level": "2",
                        "id": "aTI4X0000008OJ3WAM",
                        "icon": null,
                        "href": "https://community.workday.com/learn/strategy-roadmaps",
                        "description": "Product specific roadmaps",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Shared Demonstration Tenants",
                        "title": "Shared Demonstration Tenants",
                        "parent": "aTI4X0000008OIyWAM",
                        "order": 60,
                        "level": "2",
                        "id": "aTI4X0000008OJ4WAM",
                        "icon": null,
                        "href": "https://community.workday.com/learn/demonstration-tenants",
                        "description": "Overview and access to shared demonstration tenants",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Services Basecamp",
                        "title": "Services Basecamp",
                        "parent": "aTI4X0000008OIyWAM",
                        "order": 70,
                        "level": "2",
                        "id": "aTI4X0000008OJ5WAM",
                        "icon": null,
                        "href": "https://community.workday.com/learn/services-basecamp",
                        "description": "Services and partner specific resources",
                        "children": []
                    }
                ]
            },
            {
                "type": "Primary",
                "tooltip": "Product Hub Menu",
                "title": "Products",
                "parent": null,
                "order": 20,
                "level": "1",
                "id": "aTI4X0000008OIlWAM",
                "icon": null,
                "href": null,
                "description": "Product hubs organize content and iteraction opportunities by product",
                "children": [
                    {
                        "type": "Primary",
                        "tooltip": "Human Capital Management hub",
                        "title": "Human Capital Management",
                        "parent": "aTI4X0000008OIlWAM",
                        "order": 10,
                        "level": "2",
                        "id": "aTI4X0000008OImWAM",
                        "icon": null,
                        "href": "https://community.workday.com/products/human-capital-management",
                        "description": "Specific product hub navigation link",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Financial Management hub",
                        "title": "Financial Management",
                        "parent": "aTI4X0000008OIlWAM",
                        "order": 20,
                        "level": "2",
                        "id": "aTI4X0000008OInWAM",
                        "icon": null,
                        "href": "https://community.workday.com/products/financial-management",
                        "description": "Specific product hub navigation link",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Workday Payroll hub",
                        "title": "Workday Payroll",
                        "parent": "aTI4X0000008OIlWAM",
                        "order": 30,
                        "level": "2",
                        "id": "aTI4X0000008OIoWAM",
                        "icon": null,
                        "href": "https://community.workday.com/products/workday-payroll",
                        "description": "Specific product hub navigation link",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Platform & Product Extensions",
                        "title": "Platform & Product Extensions",
                        "parent": "aTI4X0000008OIlWAM",
                        "order": 40,
                        "level": "2",
                        "id": "aTI4X0000008OIpWAM",
                        "icon": null,
                        "href": "https://community.workday.com/products/platform-and-product-extensions",
                        "description": "Specific product hub navigation link",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Workforce Management hub",
                        "title": "Workforce Management",
                        "parent": "aTI4X0000008OIlWAM",
                        "order": 60,
                        "level": "2",
                        "id": "aTI4X0000008OIrWAM",
                        "icon": null,
                        "href": "https://community.workday.com/products/workforce-management",
                        "description": "Specific product hub navigation link",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "View all product hubs",
                        "title": "All Products",
                        "parent": "aTI4X0000008OIlWAM",
                        "order": 70,
                        "level": "2",
                        "id": "aTI4X0000008OIsWAM",
                        "icon": null,
                        "href": "https://community.workday.com/products/all-products",
                        "description": "Links to all available product hubs",
                        "children": []
                    }
                ]
            },
            {
                "type": "Primary",
                "tooltip": "Collaborate menu",
                "title": "Collaborate",
                "parent": null,
                "order": 30,
                "level": "1",
                "id": "aTI4X0000008OJFWA2",
                "icon": null,
                "href": null,
                "description": "Interactive user generated content opportunities",
                "children": [
                    {
                        "type": "Primary",
                        "tooltip": "Forums",
                        "title": "Discuss",
                        "parent": "aTI4X0000008OJFWA2",
                        "order": 10,
                        "level": "2",
                        "id": "aTI4X0000008OJGWA2",
                        "icon": null,
                        "href": "https://collaborate.workday.com/t5/Discuss/ct-p/Category_Discuss",
                        "description": "Landing page for forums available to user",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Brainstorms",
                        "title": "Innovate",
                        "parent": "aTI4X0000008OJFWA2",
                        "order": 20,
                        "level": "2",
                        "id": "aTI4X0000008OJHWA2",
                        "icon": null,
                        "href": "https://collaborate.workday.com/t5/Innovate/ct-p/Category_Innovate",
                        "description": "Landing page for viewing and creating brainstorms for improving Workday",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Events",
                        "title": "Connect",
                        "parent": "aTI4X0000008OJFWA2",
                        "order": 30,
                        "level": "2",
                        "id": "aTI4X0000008OJIWA2",
                        "icon": null,
                        "href": "https://collaborate.workday.com/t5/Connect/ct-p/Category_Connect",
                        "description": "Upcoming events a user may attend",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "User Groups",
                        "title": "Partners",
                        "parent": "aTI4X0000008OJFWA2",
                        "order": 40,
                        "level": "2",
                        "id": "aTI4X0000008OJJWA2",
                        "icon": null,
                        "href": "https://collaborate.workday.com/t5/Partners/ct-p/Category_Partners",
                        "description": "Organize partner-specific resources and participation opportunities",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Design Partner Opportunities",
                        "title": "Discover",
                        "parent": "aTI4X0000008OJFWA2",
                        "order": 50,
                        "level": "2",
                        "id": "aTI4X0000008OJKWA2",
                        "icon": null,
                        "href": "https://collaborate.workday.com/t5/Discover/ct-p/Category_Discover",
                        "description": "Member news and updates and collaborate resources",
                        "children": []
                    }
                ]
            },
            {
                "type": "Primary",
                "tooltip": "Feature Release menu",
                "title": "Feature Release",
                "parent": null,
                "order": 40,
                "level": "1",
                "id": "aTI4X0000008OItWAM",
                "icon": null,
                "href": null,
                "description": "Nav to sites to help users with Workday Feature Releases",
                "children": [
                    {
                        "type": "Primary",
                        "tooltip": "Feature Release Guidebook",
                        "title": "Feature Release Guidebook",
                        "parent": "aTI4X0000008OItWAM",
                        "order": 10,
                        "level": "2",
                        "id": "aTI4X0000008OIuWAM",
                        "icon": null,
                        "href": "https://community.workday.com/feature-release/guidebook",
                        "description": "Framework for customers to use for our release cycle",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Scheduled Maintenance",
                        "title": "Scheduled Maintenance",
                        "parent": "aTI4X0000008OItWAM",
                        "order": 20,
                        "level": "2",
                        "id": "aTI4X0000008OIvWAM",
                        "icon": null,
                        "href": "https://community.workday.com/feature-release/maintenance",
                        "description": "Planned Maintenance windows",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Release Center",
                        "title": "Release Center",
                        "parent": "aTI4X0000008OItWAM",
                        "order": 30,
                        "level": "2",
                        "id": "aTI4X0000008OIwWAM",
                        "icon": null,
                        "href": "https://community.workday.com/feature-release/release-center",
                        "description": "The Release Center organizes release details for the most recent feature release. The Release Prep Center replaces it for the 6 weeks approaching a new release, and features the next release.",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Release Notes",
                        "title": "Release Notes",
                        "parent": "aTI4X0000008OItWAM",
                        "order": 40,
                        "level": "2",
                        "id": "aTI4X0000008OIxWAM",
                        "icon": null,
                        "href": "https://community.workday.com/feature-release/release-notes",
                        "description": "Comprehensive release notes",
                        "children": []
                    }
                ]
            },
            {
                "type": "Primary",
                "tooltip": "Get Help menu",
                "title": "Get Help",
                "parent": null,
                "order": 50,
                "level": "1",
                "id": "aTI4X0000008OJLWA2",
                "icon": null,
                "href": null,
                "description": "Self-service and solution finding resources",
                "children": [
                    {
                        "type": "Primary",
                        "tooltip": "Datacenter Status",
                        "title": "Datacenter Status",
                        "parent": "aTI4X0000008OJLWA2",
                        "order": 10,
                        "level": "2",
                        "id": "aTI4X0000008OJMWA2",
                        "icon": null,
                        "href": "https://community.workday.com/get-help/datacenter-status",
                        "description": "Summary on the current health status of Workday data centers",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Troubleshooting Resources",
                        "title": "Troubleshooting Resources",
                        "parent": "aTI4X0000008OJLWA2",
                        "order": 20,
                        "level": "2",
                        "id": "aTI4X0000008OJNWA2",
                        "icon": null,
                        "href": "https://community.workday.com/get-help/troubleshooting-resources",
                        "description": "Organized list of resources and links to help troubleshooting",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Customer Alerts",
                        "title": "Customer Alerts",
                        "parent": "aTI4X0000008OJLWA2",
                        "order": 30,
                        "level": "2",
                        "id": "aTI4X0000008OJOWA2",
                        "icon": null,
                        "href": "https://community.workday.com/get-help/customer-alerts",
                        "description": "Support alerts to customers related to operations, defects and other product-specific information",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Services Alerts",
                        "title": "Services Alerts",
                        "parent": "aTI4X0000008OJLWA2",
                        "order": 40,
                        "level": "2",
                        "id": "aTI4X0000008OJPWA2",
                        "icon": null,
                        "href": "https://community.workday.com/get-help/services-alerts",
                        "description": "Support alerts to staff and partners related to operations, defects and other product-specific information",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Training Coordinator Hub",
                        "title": "Training Coordinator Hub",
                        "parent": "aTI4X0000008OJLWA2",
                        "order": 60,
                        "level": "2",
                        "id": "aTI4X0000008OJQWA2",
                        "icon": null,
                        "href": "https://community.workday.com/get-help/training-coordinator-hub",
                        "description": "Training and resources for users in the Training Coordinator Workday Support Role",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "NSC Hub",
                        "title": "NSC Hub",
                        "parent": "aTI4X0000008OJLWA2",
                        "order": 70,
                        "level": "2",
                        "id": "aTI4X0000008OJRWA2",
                        "icon": null,
                        "href": "https://community.workday.com/get-help/nsc-hub",
                        "description": "Training and resources for users in the Named Support Contact Workday Support role",
                        "children": []
                    }
                ]
            },
            {
                "type": "Primary",
                "tooltip": "Manage menu",
                "title": "Manage",
                "parent": null,
                "order": 60,
                "level": "1",
                "id": "aTI4X0000008OJ6WAM",
                "icon": null,
                "href": null,
                "description": "Support and Workday Role Administrative Functions",
                "children": [
                    {
                        "type": "Primary",
                        "tooltip": "Cases",
                        "title": "Cases",
                        "parent": "aTI4X0000008OJ6WAM",
                        "order": 10,
                        "level": "2",
                        "id": "aTI4X0000008OJ7WAM",
                        "icon": null,
                        "href": "https://workdayinc.force.com/workdaycustomercenter/apex/CC_CommunityCases",
                        "description": "Customer case portal",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Users",
                        "title": "Users",
                        "parent": "aTI4X0000008OJ6WAM",
                        "order": 20,
                        "level": "2",
                        "id": "aTI4X0000008OJ8WAM",
                        "icon": null,
                        "href": "https://workdayinc.force.com/CommunityAccess/s/user-management",
                        "description": "Org Administration and Customer Center Contact management",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": null,
                        "title": "Contacts Management",
                        "parent": "aTI4X0000008OJ6WAM",
                        "order": 30,
                        "level": "2",
                        "id": "aTI4X0000008OJ9WAM",
                        "icon": null,
                        "href": "https://workdayinc.force.com/workdaycustomercenter/apex/CC_NSCAdministration",
                        "description": "Support contact mangement",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Training",
                        "title": "Training",
                        "parent": "aTI4X0000008OJ6WAM",
                        "order": 40,
                        "level": "2",
                        "id": "aTI4X0000008OJAWA2",
                        "icon": null,
                        "href": "https://workdayinc.force.com/workdaycustomercenter/apex/LMS_TrainingUnits",
                        "description": "Training administration tasks",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Tenants",
                        "title": "Tenants",
                        "parent": "aTI4X0000008OJ6WAM",
                        "order": 50,
                        "level": "2",
                        "id": "aTI4X0000008OJBWA2",
                        "icon": null,
                        "href": "https://workdayinc.force.com/workdaycustomercenter/apex/CC_CommunityTenants",
                        "description": "Tenant request and management",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "My Organization",
                        "title": "My Organization",
                        "parent": "aTI4X0000008OJ6WAM",
                        "order": 60,
                        "level": "2",
                        "id": "aTI4X0000008OJCWA2",
                        "icon": null,
                        "href": "https://workdayinc.force.com/CommunityAccess/s/",
                        "description": "Organization profile management",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Reports",
                        "title": "Reports",
                        "parent": "aTI4X0000008OJ6WAM",
                        "order": 70,
                        "level": "2",
                        "id": "aTI4X0000008OJEWA2",
                        "icon": null,
                        "href": "https://workdayinc.force.com/workdaycustomercenter/00O/o",
                        "description": "Support oriented reports",
                        "children": []
                    },
                    {
                        "type": "Primary",
                        "tooltip": "Reports",
                        "title": "Content Library",
                        "parent": "aTI4X0000008OJ6WAM",
                        "order": 80,
                        "level": "2",
                        "id": "aTI4X0000008OJDWA2",
                        "icon": null,
                        "href": "https://workdayinc.force.com/workdaycustomercenter/apex/CC_ListContent",
                        "description": "Support oriented reports including audit and compliance",
                        "children": []
                    }
                ]
            }
        ]
    },
    "notification": {
        "redirectUrl": "https://workdayinc.force.com/workdaycustomercenter/apex/CC_ProactiveNotifications",
        "notify": null
    },
    "contactInformation": null,
    "lastAccessedDate": "12/12/2022 17:03:44"
}

var skipTo = '';
var sticky = true;

ReactDOM.render(React.createElement(Cmty.GlobalHeader, { menus: default_header_data, skipTo, sticky, searchProps: { redirectPath: '/global-search' } }), document.getElementById('react-header-div'));
